name: Update Json

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@v2
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'                                                   
      - name: 💿 Install pandas and xlrd                              
        run: pip install pandas xlrd openpyxl
      - name: 🍳 Update README
        run: |
          cd ${GITHUB_WORKSPACE}/scripts/
          python update.py
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "projects.json(auto generate): Updated content" || true
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git || true
